// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBuDtrZhbTsDd_C5_6r1Hqxi8GW5d0fYgg',
    appId: '1:11451740098:web:47179a4ab68f971216705b',
    messagingSenderId: '11451740098',
    projectId: 'fir-auth-7a8e3',
    authDomain: 'fir-auth-7a8e3.firebaseapp.com',
    storageBucket: 'fir-auth-7a8e3.appspot.com',
    measurementId: 'G-QKQ8F11TF8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBb5B2cQX6XaPWLC4T1TxJO85fEfr9wr1c',
    appId: '1:11451740098:android:ff95ae2233900ff416705b',
    messagingSenderId: '11451740098',
    projectId: 'fir-auth-7a8e3',
    storageBucket: 'fir-auth-7a8e3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDsKxeyPtieqXhvAXYJy5aHHBt1ta8_4os',
    appId: '1:11451740098:ios:909bea8a3e688e1116705b',
    messagingSenderId: '11451740098',
    projectId: 'fir-auth-7a8e3',
    storageBucket: 'fir-auth-7a8e3.appspot.com',
    iosBundleId: 'com.example.firebaseLogin',
  );
}
